name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  shellcheck:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - uses: nelonoel/branch-name@v1
    - name: ShellCheck
      uses: ludeeus/action-shellcheck@0.4.1
    - name: Terraform security scan
      uses: triat/terraform-security-scan@$BRANCH_NAME
      with:
        tfsec_actions_comment: false
        tfsec_actions_working_dir: "test/"
        tfsec_exclude: "AWS018,AWS006,AWS004,AWS003,AZU003"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
